import { PermissionsType, RoleType } from '../drizzle/enums';

export const DefaultPermissions: Record<RoleType, PermissionsType[]> = {
  CLIENT_USER: [
    'VIEW_SHIPMENT',
    'VIEW_DASHBOARD',
    'CREATE_SHIPMENT',
    'DELETE_SHIPMENT',
    'EDIT_SHIPMENT',
  ],
  CLIENT_SUPER_USER: [
    'VIEW_DASHBOARD',
    'VIEW_SHIPMENT',
    'VIEW_USER',
    'EDIT_SHIPMENT',
    'EDIT_USER',
    'DELETE_SHIPMENT',
    'DELETE_USER',
  ],
  WHITE_LABEL_SUB_ADMIN: [
    'VIEW_SHIPMENT',
    'VIEW_DASHBOARD',
    'CREATE_SHIPMENT',
    'DELETE_SHIPMENT',
    'EDIT_SHIPMENT',
    'EDIT_USER',
    'VIEW_USER',
    'DELETE_USER',
  ],
  WHITE_LABEL_ADMIN: [
    'VIEW_SHIPMENT',
    'VIEW_DASHBOARD',
    'CREATE_SHIPMENT',
    'DELETE_SHIPMENT',
    'EDIT_SHIPMENT',
    'EDIT_USER',
    'VIEW_USER',
    'DELETE_USER',
  ],
  SUPER_ADMIN: [
    'CREATE_SHIPMENT',
    'CREATE_USER',
    'DELETE_SHIPMENT',
    'DELETE_USER',
    'EDIT_SHIPMENT',
    'EDIT_USER',
    'VIEW_COMPANY',
    'VIEW_DASHBOARD',
    'VIEW_SHIPMENT',
    'VIEW_USER',
  ],
  SUB_ADMIN: [
    'CREATE_SHIPMENT',
    'CREATE_USER',
    'DELETE_SHIPMENT',
    'DELETE_USER',
    'EDIT_SHIPMENT',
    'EDIT_USER',
    'VIEW_COMPANY',
    'VIEW_DASHBOARD',
    'VIEW_SHIPMENT',
    'VIEW_USER',
  ],
};
