export const TYPE_OF_NOTIFICATION = {
  SYSTEM_NOTIFICATION: 'SYSTEM_NOTIFICATION',
  BOOKING_NOTIFICATION: 'USER_NOTIFICATION',
  CHAT_NOTIFICATION: 'CHAT_NOTIFICATION',
} as const;

export type TYPE_OF_NOTIFICATION_UNION = keyof typeof TYPE_OF_NOTIFICATION;
